/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.swingactividad1;

/**
 *
 * @author adhej
 */
public class SwingActividad1 extends javax.swing.JFrame {

    /**
     * Creates new form SwingActividad1
     */
    public SwingActividad1() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        titulo = new javax.swing.JLabel();
        grossIncome = new javax.swing.JLabel();
        grossAmount = new javax.swing.JTextField();
        nPagas = new javax.swing.JLabel();
        month = new javax.swing.JTextField();
        netIncome = new javax.swing.JLabel();
        calcular = new javax.swing.JButton();
        result = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        mensual = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        titulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titulo.setText("Calcular sueldo de bruto a neto");

        grossIncome.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        grossIncome.setText("sueldo bruto anual");

        grossAmount.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        grossAmount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                grossAmountActionPerformed(evt);
            }
        });

        nPagas.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        nPagas.setText("Numero de pagas anuales");
        nPagas.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);

        month.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        month.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                monthActionPerformed(evt);
            }
        });

        netIncome.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        netIncome.setText("Sueldo neto anual");

        calcular.setText("Calcular");
        calcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calcularActionPerformed(evt);
            }
        });

        result.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        result.setText(" ");

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Mensualmente");

        mensual.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        mensual.setText(" ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(97, 97, 97)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(titulo, javax.swing.GroupLayout.DEFAULT_SIZE, 174, Short.MAX_VALUE)
                    .addComponent(grossIncome, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(grossAmount)
                    .addComponent(nPagas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(netIncome, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(calcular, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(result, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(mensual, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(month))
                .addContainerGap(114, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(titulo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(grossIncome)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(grossAmount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(nPagas)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(month, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(calcular)
                .addGap(43, 43, 43)
                .addComponent(netIncome)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(result)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(mensual)
                .addContainerGap(23, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void grossAmountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_grossAmountActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_grossAmountActionPerformed

    private void calcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calcularActionPerformed
        // TODO add your handling code here:
        double sueldoBruto=Integer.parseInt(grossAmount.getText());
        double sueldoNeto;
        int mensualidades=Integer.parseInt(month.getText());
        double sueldoMensual;
        if (sueldoBruto<12450){
            sueldoNeto=sueldoBruto*0.81;
            result.setText(String.valueOf(sueldoNeto));
            sueldoMensual=sueldoNeto/mensualidades;
            mensual.setText(String.valueOf(sueldoMensual));
        }else if(sueldoBruto>=12450 && sueldoBruto<20200){
            sueldoNeto=sueldoBruto*0.76;
            result.setText(String.valueOf(sueldoNeto));
            sueldoMensual=sueldoNeto/mensualidades;
            mensual.setText(String.valueOf(sueldoMensual));
        }else if(sueldoBruto>=20200 && sueldoBruto<35200){
            sueldoNeto=sueldoBruto*0.7;
            result.setText(String.valueOf(sueldoNeto));
            sueldoMensual=sueldoNeto/mensualidades;
            mensual.setText(String.valueOf(sueldoMensual));
        }else if(sueldoBruto>=35200 && sueldoBruto<60000){
            sueldoNeto=sueldoBruto*0.63;
            result.setText(String.valueOf(sueldoNeto));
            sueldoMensual=sueldoNeto/mensualidades;
            mensual.setText(String.valueOf(sueldoMensual));
        }else if(sueldoBruto>=60000 && sueldoBruto<300000){
            sueldoNeto=sueldoBruto*0.55;
            result.setText(String.valueOf(sueldoNeto));
            sueldoMensual=sueldoNeto/mensualidades;
            mensual.setText(String.valueOf(sueldoMensual));
        }else{
            sueldoNeto=sueldoBruto*0.53;
            result.setText(String.valueOf(sueldoNeto));
            sueldoMensual=sueldoNeto/mensualidades;
            mensual.setText(String.valueOf(sueldoMensual));
        }
                
    }//GEN-LAST:event_calcularActionPerformed

    private void monthActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_monthActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_monthActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SwingActividad1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SwingActividad1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SwingActividad1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SwingActividad1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SwingActividad1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton calcular;
    private javax.swing.JTextField grossAmount;
    private javax.swing.JLabel grossIncome;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel mensual;
    private javax.swing.JTextField month;
    private javax.swing.JLabel nPagas;
    private javax.swing.JLabel netIncome;
    private javax.swing.JLabel result;
    private javax.swing.JLabel titulo;
    // End of variables declaration//GEN-END:variables
}
